### PR TITLE
Add oracle constant

### PR DESCRIPTION
**Pull request by mikollaay**

### CODE REVIEW

**Comment by dmcghan** [comment]
@mikollaay Thanks for the pull request! I noticed you removed line 169, which sets isAutoCommit to true. Was that intentional? I added it yesterday so that DML operations would be committed automatically...

**Comment by mikollaay** [comment]
I suggest to change:
options.isAutoCommit = true;  
----> 
if (options.isAutoCommit === undefined) {options.isAutoCommit = true; }

**Comment by dmcghan** [comment]
@mikollaay That's a great suggestion! Would you mind adding it? I can close this pull request and you could submit another...

**Comment by mikollaay** [comment]
Ok

**Comment by dmcghan** [comment]
@mikollaay Great, thanks!

**Comment by dmcghan** [comment]
@mikollaay Sorry, I just realized that you could modify this pull request. Let me know if you'd rather me just reopen this one...

**Comment by dmcghan** [comment]
Got it...

**Pull request merged**
